#!/bin/sh

# SPDX-License-Identifier: MPL-2.0

# Copyright © 2025 Firas Khana

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

git clone --recurse-submodules https://github.com/glaucuslinux/glaucus
git -C glaucus submodule foreach 'git checkout main'

cd glaucus

mkdir -p \
  /var/cache/rad \
  /var/lib/rad/repo

ln -fs $PWD/src /var/cache/rad
ln -fs $PWD/core /var/lib/rad/repo

for i in a2x asciidoc gtkdocize help2man ldconfig makeinfo po4a texi2dvi; do
  cp -fPp core/musl/files/true /usr/bin/$i
done

cd rad

curl -fL -o rad -s https://github.com/glaucuslinux/rad/releases/latest/download/rad-x86-64-v3-pc-linux-gnu
curl -fLOs https://github.com/glaucuslinux/rad/releases/latest/download/rad-x86-64-v3-glaucus-linux-musl

chmod 755 rad

./rad bootstrap toolchain
./rad bootstrap cross

cd ../live
./img

./mount
./umount

echo "bootstrap complete"
