#!/bin/sh

# Copyright (c) 2024, Firas Khalil Khana
# Distributed under the terms of the ISC License

rm -fr /tmp/initramfs
install -d /tmp/initramfs

rm -fr ~/initramfs

cd /tmp/initramfs

install -d dev etc run usr/bin usr/lib var
install -dm 555 proc sys

ln -sfn usr/bin bin
ln -sfn usr/lib lib
ln -sfn usr/bin sbin
ln -sfn bin usr/sbin

cp -a ~/initramfs-generator/init .

cp -a /etc/mdev.conf etc

cp -a /usr/bin/bash usr/bin
cp -a /usr/bin/blkid usr/bin
cp -a /usr/bin/kill usr/bin
cp -a /usr/bin/kmod usr/bin
cp -a /usr/bin/mdevd usr/bin
cp -a /usr/bin/mdevd-coldplug usr/bin
cp -a /usr/bin/mount usr/bin
cp -a /usr/bin/switch_root usr/bin
cp -a /usr/bin/toybox usr/bin

ln -sfn kmod usr/bin/insmod
ln -sfn kmod usr/bin/lsmod
ln -sfn kmod usr/bin/modprobe
ln -sfn bash usr/bin/sh

for i in $(toybox); do ln -sfn toybox /tmp/initramfs/usr/bin/$i; done

cp -a /usr/lib/ld-musl-x86_64.so.1 usr/lib
cp -a /usr/lib/libblkid.so* usr/lib
cp -a /usr/lib/libc.so usr/lib
cp -a /usr/lib/libcrypto* usr/lib
cp -a /usr/lib/liblz* usr/lib
cp -a /usr/lib/libmount.so* usr/lib
cp -a /usr/lib/libskarnet.so* usr/lib
cp -a /usr/lib/libterminfo.so usr/lib
cp -a /usr/lib/libz.so* usr/lib
cp -a /usr/lib/libzstd.so* usr/lib

version="$(uname -r)"

TARGETMOD="/tmp/initramfs/usr/lib/modules/$version/kernel"
install -d $TARGETMOD/drivers/usb

MODD="/usr/lib/modules/$version/kernel"

cp -ar $MODD/arch $TARGETMOD
cp -ar $MODD/crypto $TARGETMOD
cp -ar $MODD/drivers/ata $TARGETMOD/drivers
cp -ar $MODD/drivers/block $TARGETMOD/drivers
cp -ar $MODD/drivers/cdrom $TARGETMOD/drivers
cp -ar $MODD/drivers/hid $TARGETMOD/drivers
cp -ar $MODD/drivers/hwmon $TARGETMOD/drivers
cp -ar $MODD/drivers/input $TARGETMOD/drivers
cp -ar $MODD/drivers/md $TARGETMOD/drivers
cp -ar $MODD/drivers/message $TARGETMOD/drivers
cp -ar $MODD/drivers/nvme $TARGETMOD/drivers
cp -ar $MODD/drivers/scsi $TARGETMOD/drivers
cp -ar $MODD/drivers/usb/host $TARGETMOD/drivers
cp -ar $MODD/drivers/usb/storage $TARGETMOD/drivers
cp -ar $MODD/drivers/virtio $TARGETMOD/drivers
cp -ar $MODD/fs $TARGETMOD
cp -ar $MODD/lib $TARGETMOD

cp -a $MODD/../modules.builtin "/tmp/initramfs/usr/lib/modules/$version"
cp -a $MODD/../modules.builtin.modinfo "/tmp/initramfs/usr/lib/modules/$version"
cp -a $MODD/../modules.order "/tmp/initramfs/usr/lib/modules/$version"

depmod -b /tmp/initramfs $version

find . | bsdcpio -oH newc | zstd -22 --ultra -T0 --long > ~/initramfs
