#!/bin/sh

# Copyright (c) 2024, Firas Khalil Khana
# Distributed under the terms of the ISC License

ver=$(uname -r)

CERD=/var/lib/rad/clusters/cerata
MODD=/usr/lib/modules/$ver/kernel

rm -fr \
  ../gen \
  ../initramfs

rm -fr ../gen
mkdir -p ../gen
cd ../gen

mkdir -p \
  etc \
  run \
  usr/bin \
  usr/lib/modules/$ver/kernel/drivers/usb \
  var

mkdir -pm 555 \
  proc \
  sys

ln -fns usr/bin bin
ln -fns usr/lib lib
ln -fns usr/bin sbin
ln -fns bin usr/sbin

cp -af ../bubble/init .

cp -af \
  "$CERD"/fs/group \
  "$CERD"/fs/mdev.conf \
  "$CERD"/fs/passwd \
  etc

cp -af \
  /usr/bin/bash \
  /usr/bin/blkid \
  /usr/bin/mdevd \
  /usr/bin/mdevd-coldplug \
  /usr/bin/mount \
  /usr/bin/toybox \
  usr/bin

ln -fns bash usr/bin/sh

for i in $(toybox); do
  ln -fns toybox usr/bin/$i
done

cp -af \
  /usr/lib/ld-musl-x86_64.so.1 \
  /usr/lib/libblkid.so* \
  /usr/lib/libc.so \
  /usr/lib/libcrypto* \
  /usr/lib/libmount.so* \
  /usr/lib/libskarnet.so* \
  /usr/lib/libterminfo.so \
  /usr/lib/libutmps.so* \
  usr/lib

cp -af \
  "$MODD"/arch \
  "$MODD"/crypto \
  "$MODD"/fs \
  "$MODD"/lib \
  usr/lib/modules/$ver/kernel

cp -af \
  "$MODD"/drivers/ata \
  "$MODD"/drivers/block \
  "$MODD"/drivers/cdrom \
  "$MODD"/drivers/gpu \
  "$MODD"/drivers/hid \
  "$MODD"/drivers/hwmon \
  "$MODD"/drivers/input \
  "$MODD"/drivers/md \
  "$MODD"/drivers/message \
  "$MODD"/drivers/nvme \
  "$MODD"/drivers/scsi \
  "$MODD"/drivers/usb/host \
  "$MODD"/drivers/usb/storage \
  "$MODD"/drivers/virtio \
  usr/lib/modules/$ver/kernel/drivers

cp -af \
  "$MODD"/../modules.builtin \
  "$MODD"/../modules.builtin.modinfo \
  "$MODD"/../modules.order \
  usr/lib/modules/$ver

depmod -b . $ver

find . | cpio -o | zstd -22 --ultra -T0 --long > ../initramfs

cd ../bubble

rm -fr ../gen
