#!/bin/sh

# Copyright (c) 2024, Firas Khalil Khana
# Distributed under the terms of the ISC License

if [ $(id -u) -ne 0 ]; then
  echo "permission denied"
  exit 1
fi

img="../glaucus-s6-x86-64-v3-$(date +"%Y%m%d").img"
ver=6.10.6-3-cachyos

device=$(losetup -f)
partitionOne=${device}p1
partitionTwo=${device}p2

dd bs=1M count=16384 if=/dev/zero of=$img

parted -s $img mklabel gpt
parted -s $img mkpart ESP fat32 1 65
parted -s $img set 1 esp on
parted -s $img mkpart ext4 65 16384

modprobe loop

losetup -Dv
losetup -v $device $img
partx -av $device

mkfs.fat -F 32 $partitionOne
mke2fs -t ext4 $partitionTwo

rm -fr ../img
mkdir -pv ../img

mount $partitionTwo ../img

cp -afT ../cross ../img
cp -af ../src ../img/var/cache/rad

mount $partitionOne ../img/boot

depmod -b ../img $ver

booster \
  -v \
  build \
  --force \
  --compression=zstd \
  --kernel-version=$ver \
  --modules-dir=../img/usr/lib/modules/$ver \
  --config=../cerata/booster/booster.yaml \
  --universal \
  --strip \
  ../img/boot/initramfs

cp -afv ../cerata/limine/limine.conf.img ../img/boot/limine.conf
cp -afv ../cross/boot/vmlinuz ../img/boot

mkdir -pv ../img/boot/EFI/BOOT
cp -afv /usr/share/limine/BOOTX64.EFI ../img/boot/EFI/BOOT

chown -R 0:0 ../img
chown -Rv 20:20 ../img/var/log/wtmpd

umount -fRv ../img/boot
umount -fRv ../img

partx -dv $partitionOne
partx -dv $partitionTwo

losetup -d $device

rm -fr ../img
