#!/bin/sh

# Copyright (c) 2024, Firas Khalil Khana
# Distributed under the terms of the ISC License

if [ $(id -u) -ne 0 ]; then
  echo "permission denied"
  exit 1
fi

img="../glaucus-s6-x86-64-v3-$(date +"%Y%m%d").img"
ver=6.10.6-3-cachyos

IMGD=../img

dd bs=1M count=8192 if=/dev/zero of=$img

parted -s $img mklabel gpt
parted -s $img mkpart ESP fat32 1 65
parted -s $img set 1 esp on
parted -s $img mkpart ext4 65 8192

modprobe loop

losetup -D

device=$(losetup -f)
partitionOne=${device}p1
partitionTwo=${device}p2

losetup $device $img
partx -a $device

mkfs.fat -F 32 $partitionOne
mke2fs -qt ext4 $partitionTwo

rm -fr "$IMGD"
mkdir -p "$IMGD"

mount $partitionTwo "$IMGD"

cp -afT ../cross "$IMGD"
cp -af ../src "$IMGD"/var/cache/rad

mount $partitionOne "$IMGD"/boot

depmod -b "$IMGD" $ver

booster \
  build \
  --force \
  --compression=zstd \
  --kernel-version=$ver \
  --modules-dir="$IMGD"/usr/lib/modules/$ver \
  --config=../cerata/booster/booster.yaml \
  --universal \
  --strip \
  "$IMGD"/boot/initramfs

cp -af ../cerata/limine/limine.conf.img "$IMGD"/boot/limine.conf
cp -af ../cross/boot/vmlinuz "$IMGD"/boot

mkdir -p "$IMGD"/boot/EFI/BOOT
cp -af /usr/share/limine/BOOTX64.EFI "$IMGD"/boot/EFI/BOOT

chown -R 0:0 "$IMGD"
chown -R 20:20 "$IMGD"/var/log/wtmpd

umount -fR "$IMGD"/boot
umount -fR "$IMGD"

partx -d $partitionOne
partx -d $partitionTwo

losetup -d $device

rm -fr "$IMGD"

echo "img complete"
