#!/bin/sh

# Copyright (c) 2025, Firas Khalil Khana
# Distributed under the terms of the ISC License

export PATH=/usr/bin

mount -t devtmpfs devtmpfs /dev
mount -t proc proc /proc
mount -t sysfs sys /sys

modprobe loop

mdevd -C > /dev/null 2>&1 & pid=$!

until device=$(blkid -L GLAUCUS) && mount -o ro $device /media/iso; do
  sleep 1
done

mount -t erofs /media/iso/fs /media/fs-ro
mount -o size=1G -t tmpfs tmpfs /media/fs-rw

mkdir -p \
  /media/fs-rw/upper \
  /media/fs-rw/work

mount -o lowerdir=/media/fs-ro,upperdir=/media/fs-rw/upper,workdir=/media/fs-rw/work -t overlay overlay /mnt/root

for i in dev proc sys; do
  mount -M /$i /mnt/root/$i
done
for i in fs-ro fs-rw iso; do
  mount -M /media/$i /mnt/root/mnt/$i
done

kill $pid

exec switch_root /mnt/root /usr/bin/init
