#!/bin/sh

# Copyright (c) 2024, Firas Khalil Khana
# Distributed under the terms of the ISC License

export PATH=/usr/bin:/bin

mount -m -t devtmpfs devtmpfs /dev
mount -t proc proc /proc
mount -t sysfs sys /sys

modprobe loop

mdevd -C > /dev/null 2>&1 & pid=$!

until label=$(blkid -L GLAUCUS) && mount -m -o ro $label /media/cdrom; do
  sleep 1
done

mount -m -t erofs /media/cdrom/rootfs /media/rootfs-ro

mount -m -o size=1G -t tmpfs tmpfs /media/rootfs-rw

install -d /media/rootfs-rw/upper /media/rootfs-rw/work

mount -m -o lowerdir=/media/rootfs-ro,upperdir=/media/rootfs-rw/upper,workdir=/media/rootfs-rw/work -t overlay overlay /mnt/root

mount -M -m /media/cdrom /mnt/root/mnt/cdrom
mount -M -m /media/rootfs-ro /mnt/root/mnt/rootfs-ro
mount -M -m /media/rootfs-rw /mnt/root/mnt/rootfs-rw

kill $pid

exec switch_root /mnt/root /bin/init
