#!/bin/sh

# Copyright (c) 2025, Firas Khalil Khana
# Distributed under the terms of the ISC License

if [ $(id -u) -ne 0 ]; then
  echo "permission denied"
  exit 1
fi

iso="../glaucus-s6-x86-64-v3-$(date +"%Y%m%d").iso"
ver=6.10.6-3-cachyos

ISOD=../iso
PKGD=../pkg/skel

rm -fr "$ISOD"

mkdir -p \
  "$ISOD"/EFI/BOOT \
  "$ISOD"/limine \
  "$ISOD"/tmp

cp -af \
  ../initramfs \
  ../cross/boot/vmlinuz \
  "$ISOD"

cp -af /usr/share/limine/BOOTX64.EFI "$ISOD"/EFI/BOOT
cp -af ../cerata/limine/limine.conf "$ISOD"/limine
cp -af \
  /usr/share/limine/limine-bios.sys \
  /usr/share/limine/limine-bios-cd.bin \
  /usr/share/limine/limine-uefi-cd.bin \
  "$ISOD"/limine

for i in $(ls "$PKGD"); do
  bsdtar -xmPf "$PKGD"/$i/*.tar.zst -C "$ISOD"/tmp
done

mkdir -pv \
  "$ISOD"/tmp/mnt/fs-ro \
  "$ISOD"/tmp/mnt/fs-rw \
  "$ISOD"/tmp/mnt/iso

cp -af ../rad/src/rad "$ISOD"/tmp/usr/bin

rm -fr \
  "$ISOD"/tmp/boot \
  "$ISOD"/tmp/usr/share/bash-completion \
  "$ISOD"/tmp/usr/share/doc \
  "$ISOD"/tmp/usr/share/info \
  "$ISOD"/tmp/usr/share/locale \
  "$ISOD"/tmp/usr/share/man

depmod -b "$ISOD"/tmp $ver

chown -R 0:0 "$ISOD"
chown -R 20:20 "$ISOD"/tmp/var/log/wtmpd

mkfs.erofs "$ISOD"/fs "$ISOD"/tmp

rm -fr "$ISOD"/tmp

xorriso \
  -as mkisofs \
  -o $iso \
  -iso-level 3 \
  -l \
  -r \
  -J \
  -joliet-long \
  -hfsplus \
  -apm-block-size 2048 \
  -V GLAUCUS \
  -P glaucus \
  -A glaucus \
  -p glaucus \
  -b limine/limine-bios-cd.bin \
  -boot-load-size 4 \
  -no-emul-boot \
  -boot-info-table \
  --efi-boot limine/limine-uefi-cd.bin \
  --protective-msdos-label \
  -efi-boot-part \
  --efi-boot-image \
  "$ISOD"

limine bios-install $iso

rm -fr "$ISOD"

echo "iso complete"
