#!/bin/sh

# Copyright (c) 2024, Firas Khalil Khana
# Distributed under the terms of the ISC License

if [ $(id -u) -ne 0 ]; then
  echo "permission denied"
  exit 1
fi

iso="../glaucus-s6-x86-64-v3-$(date +"%Y%m%d").iso"

rm -frv ../iso
mkdir -pv \
  ../iso/EFI/BOOT \
  ../iso/limine \
  ../iso/tmp

cp -afv \
  ../initramfs \
  ../cross/usr/lib/modules/6.10.6-3-cachyos/vmlinuz \
  ../iso

cp -afv /usr/share/limine/BOOTX64.EFI ../iso/EFI/BOOT
cp -afv ../cerata/limine/limine.conf.iso ../iso/limine/limine.conf
cp -afv \
  /usr/share/limine/limine-bios.sys \
  /usr/share/limine/limine-bios-cd.bin \
  /usr/share/limine/limine-uefi-cd.bin \
  ../iso/limine

../rad/rad -ci skel

rm -frv ../iso/tmp/boot

chown -R 0:0 ../iso
chown -Rv 20:20 ../iso/tmp/var/log/wtmpd

mkfs.erofs ../iso/fs ../iso/tmp

rm -fr ../iso/tmp

xorriso \
  -as mkisofs \
  -o $iso \
  -iso-level 3 \
  -l \
  -r \
  -J \
  -joliet-long \
  -hfsplus \
  -apm-block-size 2048 \
  -V GLAUCUS \
  -P glaucus \
  -A glaucus \
  -p glaucus \
  -b limine/limine-bios-cd.bin \
  -boot-load-size 4 \
  -no-emul-boot \
  -boot-info-table \
  --efi-boot limine/limine-uefi-cd.bin \
  --protective-msdos-label \
  -efi-boot-part \
  --efi-boot-image \
  -vv \
  ../iso

rm -fr ../iso

limine bios-install $iso
