#!/bin/sh

# Copyright (c) 2024, Firas Khalil Khana
# Distributed under the terms of the ISC License

if [ $(id -u) -ne 0 ]; then
  echo "permission denied"
  exit 1
fi

iso="../glaucus-s6-x86-64-v3-$(date +"%Y%m%d").iso"

ISOD=../iso

rm -fr "$ISOD"

mkdir -p \
  "$ISOD"/EFI/BOOT \
  "$ISOD"/limine \
  "$ISOD"/tmp

cp -af \
  ../initramfs \
  ../cross/usr/lib/modules/6.10.6-3-cachyos/vmlinuz \
  "$ISOD"

cp -af /usr/share/limine/BOOTX64.EFI "$ISOD"/EFI/BOOT
cp -af ../cerata/limine/limine.conf.iso "$ISOD"/limine/limine.conf
cp -af \
  /usr/share/limine/limine-bios.sys \
  /usr/share/limine/limine-bios-cd.bin \
  /usr/share/limine/limine-uefi-cd.bin \
  "$ISOD"/limine

../rad/rad -ci skel

rm -fr "$ISOD"/tmp/boot

chown -R 0:0 "$ISOD"
chown -R 20:20 "$ISOD"/tmp/var/log/wtmpd

mkfs.erofs "$ISOD"/fs "$ISOD"/tmp

rm -fr "$ISOD"/tmp

xorriso \
  -as mkisofs \
  -o $iso \
  -iso-level 3 \
  -l \
  -r \
  -J \
  -joliet-long \
  -hfsplus \
  -apm-block-size 2048 \
  -V GLAUCUS \
  -P glaucus \
  -A glaucus \
  -p glaucus \
  -b limine/limine-bios-cd.bin \
  -boot-load-size 4 \
  -no-emul-boot \
  -boot-info-table \
  --efi-boot limine/limine-uefi-cd.bin \
  --protective-msdos-label \
  -efi-boot-part \
  --efi-boot-image \
  "$ISOD"

rm -fr "$ISOD"

limine bios-install $iso

echo "iso complete"
