#!/bin/sh

# Copyright (c) 2025, Firas Khalil Khana
# Distributed under the terms of the ISC License

exec qemu-system-x86_64 \
  -machine q35,accel=kvm \
  -cpu host \
  -smp 4 \
  -boot order=d \
  -m 4G \
  -name glaucus \
  -display gtk,gl=on \
  -vga qxl \
  -rtc base=localtime \
  -bios /usr/share/ovmf/x64/OVMF.4m.fd \
  -cdrom "$1"
