#!/bin/sh

# SPDX-License-Identifier: MPL-2.0

# Copyright © 2025 Firas Khana

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

exec qemu-system-x86_64 \
  -machine q35,accel=kvm \
  -cpu host \
  -smp 4 \
  -boot order=d \
  -m 4G \
  -name glaucus \
  -cdrom "$1" \
  -display gtk,gl=on \
  -vga qxl \
  -rtc base=localtime \
  -bios /usr/share/ovmf/x64/OVMF.4m.fd
