#!/bin/sh

# SPDX-License-Identifier: MPL-2.0

# Copyright © 2025 Firas Khana

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

MNTD=../mnt

umount -fR $MNTD
losetup -D

sleep 3

rm -fR $MNTD

echo "umount complete"
